AWSTemplateFormatVersion: 2010-09-09
Description: Template to create the EKS Node IAM Role

Parameters:
  EnvironmentName:
    Type: String

  KubernetesVersionNumber:
    Type: Number

  BuildNumber:
    Type: Number

  NodeGroupName:
    Type: String

Resources:
  NodeIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-${AWS::Region}-EKS-${KubernetesVersionNumber}-${BuildNumber}-${NodeGroupName}
      Description: !Sub 
      - EKS Node IAM Role for '${ClusterName}/${EnvironmentName}-EKS-${KubernetesVersionNumber}-${BuildNumber}-${NodeGroupName}' Node Group.
      - ClusterName: !Sub ${EnvironmentName}-${AWS::Region}-EKS-Cluster
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: ec2.amazonaws.com
      Policies:
      - PolicyName: cfn-eks-s3-asg
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - cloudformation:DescribeStackResource
            - eks:DescribeNodegroup
            - s3:GetObject
            - autoscaling:DescribeAutoScalingNotificationTypes
            - autoscaling:DescribeLifecycleHookTypes
            - autoscaling:DescribeAutoScalingInstances
            - autoscaling:DescribeTerminationPolicyTypes
            - autoscaling:DescribeScalingProcessTypes
            - autoscaling:DescribePolicies
            - autoscaling:DescribeTags
            - autoscaling:DescribeLaunchConfigurations
            - autoscaling:DescribeMetricCollectionTypes
            - autoscaling:DescribeLoadBalancers
            - autoscaling:DescribeLifecycleHooks
            - autoscaling:DescribeAdjustmentTypes
            - autoscaling:DescribeScalingActivities
            - autoscaling:DescribeAutoScalingGroups
            - autoscaling:DescribeAccountLimits
            - autoscaling:DescribeScheduledActions
            - autoscaling:DescribeLoadBalancerTargetGroups
            - autoscaling:DescribeNotificationConfigurations
            - autoscaling:DescribeInstanceRefreshes
            - autoscaling:SetDesiredCapacity
            - autoscaling:TerminateInstanceInAutoScalingGroup
            Resource: "*"
      ManagedPolicyArns:
      - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonEKS_CNI_Policy
      - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore
      - !Sub arn:${AWS::Partition}:iam::aws:policy/CloudWatchAgentServerPolicy
      - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonEKSClusterPolicy
      - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonEKSServicePolicy
      - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonEKSVPCResourceController
      Path: /

Outputs:
  NodeIAMRoleArn:
    Description: Node IAM Role ARN
    Value: !GetAtt NodeIAMRole.Arn
    Export:
      Name: !Sub ${EnvironmentName}-EKS-${KubernetesVersionNumber}-${BuildNumber}-${NodeGroupName}-NodeIAMRoleArn