AWSTemplateFormatVersion: 2010-09-09
Description: Template to register the EKS Node IAM Role

Parameters:
  EnvironmentName:
    Type: String

  KubernetesVersionNumber:
    Type: Number

  BuildNumber:
    Type: Number

  NodeGroupName:
    Type: String

Resources:
  RegisterNodeIamRole:
    Type: Custom::RegisterNodeIamRole
    Properties:
      ServiceToken: 
        Fn::ImportValue: !Sub ${EnvironmentName}-EKS-ConfigManagerArn
      NodeIamRoleArn: 
        Fn::ImportValue: !Sub ${EnvironmentName}-EKS-${KubernetesVersionNumber}-${BuildNumber}-${NodeGroupName}-NodeIAMRoleArn
        
Outputs:
  RegistrationStatus:
    Description: Node IAM Role registration status
    Value: !GetAtt RegisterNodeIamRole.Response