version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - set -x
      - curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/darwin/amd64/kubectl
      - chmod +x kubectl
      - mkdir -p ~/.local/bin/kubectl
      - mv ./kubectl ~/.local/bin/kubectl
      - echo 'export PATH=$PATH:~/.local/bin/kubectl' >> ~/.bashrc
  pre_build:
    commands:
      - aws eks update-kubeconfig --name $CLUSTER_NAME
  build:
    commands:
      - chmod +x $COMMAND
      - ./$COMMAND $ARGUMENTS