AWSTemplateFormatVersion: 2010-09-09
Description: Template to create the EKS Cluster and the required EKS Service Role

Parameters:
  EnvironmentName:
    Type: String

  KmsKeyArn:
    Type: String

  KubernetesVersion:
    Type: String

  EndpointPublicAccess:
    Type: String
    Description: Cluster API is accessible from the public network (Internet).
    Default: false
    AllowedValues:
      - true
      - false

  EndpointPrivateAccess:
    Type: String
    Description: Cluster API is accessible from private network only.
    Default: true
    AllowedValues:
      - true
      - false

  Subnets:
    Type: CommaDelimitedList

  ControlPlaneCidr:
    Type: String
  
Resources:
  ClusterServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-${AWS::Region}-EKS-ClusterServiceRole
      Description: !Sub EKS Cluster Service Role for '${EnvironmentName}' environment in ${AWS::Region} region.
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
      Policies:
      - PolicyName: DenyRevokeSecurityGroupRuleChange
        PolicyDocument:
          Statement:
          - Action:
            - ec2:RevokeSecurityGroupIngress
            - ec2:RevokeSecurityGroupEgress
            Resource: "*"
            Effect: Deny
      - PolicyName: kms
        PolicyDocument:
          Statement:
          - Action: kms:*
            Resource: !Ref KmsKeyArn
            Effect: Allow
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: eks.amazonaws.com
      Tags:
      - Key: managed_by
        Value: ML_Cloud_Infra_Services
      - Key: Name
        Value: !Sub ${EnvironmentName}-${AWS::Region}-EKS-ClusterServiceRole

  Cluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Sub ${EnvironmentName}-${AWS::Region}-EKS-Cluster
      Version: !Ref KubernetesVersion
      RoleArn: !GetAtt ClusterServiceRole.Arn
      EncryptionConfig:
        - Provider:
            KeyArn:
              !Ref KmsKeyArn
          Resources:
          - secrets
      KubernetesNetworkConfig:
        ServiceIpv4Cidr: !Ref ControlPlaneCidr
      ResourcesVpcConfig:
        SubnetIds: !Ref Subnets
        SecurityGroupIds:
        - Fn::ImportValue: !Sub ${EnvironmentName}-EKS-ClusterSecurityGroupId
        EndpointPublicAccess: !Ref EndpointPublicAccess
        EndpointPrivateAccess: !Ref EndpointPrivateAccess

  OidcProvider:
    Type: AWS::IAM::OIDCProvider
    DependsOn:
      - Cluster
    Properties:
      Url: !GetAtt Cluster.OpenIdConnectIssuerUrl
      ThumbprintList:
        - 9e99a48a9960b14926bb7f3b02e22da2b0ab7280
      ClientIdList:
        - sts.amazonaws.com

Outputs:
  AmxControlPlaneOpenIdConnectIssuerUrl:
    Description: 'EKS Control Plane Issue URL'
    Value: !Select [1, !Split ["https://", !GetAtt Cluster.OpenIdConnectIssuerUrl]]
    Export:
      Name: !Sub ${EnvironmentName}-EKS-OidcProvider
